language: cpp
compiler:
  - gcc
  - clang
before_script:
  - cd ../
  - git clone https://github.com/opencv/opencv.git
  - mkdir build-opencv
  - cd build-opencv
  - cmake ../opencv
script:
  - make -j5
notifications:
  email: false
